/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Hello: typeof import('./pages/Hello')['default']
  const Home: typeof import('./pages/Home')['default']
}
